name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 2.0.0)'
        required: true
        default: '2.0.0'
      prerelease:
        description: 'Mark as pre-release?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  manual-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Update version in files
        run: |
          # Update setup.py
          sed -i "s/version=\".*\"/version=\"${{ github.event.inputs.version }}\"/" setup.py
          
          # Update pyproject.toml
          sed -i "s/^version = .*/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
          
          echo "Updated version to ${{ github.event.inputs.version }}"

      - name: Build package
        run: |
          python -m build
          echo "Build complete!"
          ls -lah dist/

      - name: Create release notes
        run: |
          cat > release_notes.md << 'EOF'
          # ADTUI v${{ github.event.inputs.version }}
          
          ## Installation
          
          ```bash
          # Download the wheel file, then:
          pip install adtui-${{ github.event.inputs.version }}-py3-none-any.whl
          ```
          
          Or install directly from Gitea:
          ```bash
          pip install git+${{ github.server_url }}/${{ github.repository }}.git@v${{ github.event.inputs.version }}
          ```
          
          ## Quick Start
          
          1. Download and rename config.ini.example to config.ini
          2. Edit config.ini with your AD server details
          3. Run: `adtui`
          
          ## Documentation
          
          - README.md - Full documentation
          - COMMANDS.md - Command reference
          - FEATURES.md - Feature list
          
          ## Requirements
          
          - Python 3.8+
          - ldap3>=2.9.1
          - textual>=0.40.0
          
          ---
          
          Released manually on $(date +%Y-%m-%d)
          EOF

      - name: Create Git Tag
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*,config.ini.example,README.md,COMMANDS.md,FEATURES.md"
          tag: v${{ github.event.inputs.version }}
          name: ADTUI v${{ github.event.inputs.version }}
          bodyFile: release_notes.md
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          token: ${{ secrets.GITEA_TOKEN }}
          allowUpdates: true

      - name: Success message
        run: |
          echo "✅ Release v${{ github.event.inputs.version }} created successfully!"
          echo ""
          echo "📦 Release URL: ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ github.event.inputs.version }}"
          echo ""
          echo "Share with your coworkers:"
          echo "pip install git+${{ github.server_url }}/${{ github.repository }}.git@v${{ github.event.inputs.version }}"
